//! Model hyper-parameters.
//!
//! Defaults follow Section 4.1 ("Implementation details") of the paper:
//! 4 DiT blocks with hidden size 512 and 2 attention heads, a UTTE with
//! 32 universal timbre tokens of hidden size 256 and a 4-head
//! cross-attention module, 40 ms chunks on 16 kHz audio, and layer-wise
//! FRC receptive fields P = [2, 2, 1, 1], F = [1, 0, 0, 0].

/// Configuration of the DiT decoder.
#[derive(Debug, Clone)]
pub struct DecoderConfig {
    /// Number of mel-spectrogram bins generated by the decoder.
    pub n_mels: usize,
    /// Dimension of the (timbre-aware) bottleneck features used as the
    /// content condition.
    pub bnf_dim: usize,
    /// Hidden size of the DiT blocks.
    pub hidden_dim: usize,
    /// Number of self-attention heads per DiT block.
    pub num_heads: usize,
    /// Number of DiT blocks. Must equal `past_receptive.len()` and
    /// `future_receptive.len()`.
    pub num_layers: usize,
    /// Number of mel frames per FRC chunk (40 ms of audio).
    pub chunk_frames: usize,
    /// Per-layer number of past chunks each chunk may attend to (P_l).
    pub past_receptive: Vec<usize>,
    /// Per-layer number of future chunks each chunk may attend to (F_l).
    pub future_receptive: Vec<usize>,
    /// Dimension of the global speaker embedding (ECAPA-TDNN: 192).
    pub speaker_dim: usize,
    /// Hidden size of the timestep-embedding MLP.
    pub time_embed_dim: usize,
}

impl Default for DecoderConfig {
    fn default() -> Self {
        Self {
            n_mels: 80,
            bnf_dim: 256,
            hidden_dim: 512,
            num_heads: 2,
            num_layers: 4,
            chunk_frames: 4,
            past_receptive: vec![2, 2, 1, 1],
            future_receptive: vec![1, 0, 0, 0],
            speaker_dim: 192,
            time_embed_dim: 512,
        }
    }
}

/// Configuration of the universal timbre token encoder (UTTE).
#[derive(Debug, Clone)]
pub struct UtteConfig {
    /// Dimension of the global speaker embedding fed to the MLPs.
    pub speaker_dim: usize,
    /// Dimension of the bottleneck features used as queries.
    pub bnf_dim: usize,
    /// Number of universal timbre tokens (K).
    pub num_tokens: usize,
    /// Hidden size of the UTT key/value pairs and the cross-attention.
    pub hidden_dim: usize,
    /// Number of cross-attention heads.
    pub num_heads: usize,
}

impl Default for UtteConfig {
    fn default() -> Self {
        Self {
            speaker_dim: 192,
            bnf_dim: 256,
            num_tokens: 32,
            hidden_dim: 256,
            num_heads: 4,
        }
    }
}

// The audio front-end configuration is engine-agnostic and lives in
// `vc-core`; re-exported here so `meanvc2::config::MelConfig` keeps working.
pub use vc_core::config::MelConfig;

/// Top-level configuration bundling every sub-module.
#[derive(Debug, Clone, Default)]
pub struct MeanVc2Config {
    pub decoder: DecoderConfig,
    pub utte: UtteConfig,
    pub mel: MelConfig,
}

impl MeanVc2Config {
    /// Validates cross-field invariants.
    pub fn validate(&self) -> Result<(), crate::Error> {
        if self.decoder.past_receptive.len() != self.decoder.num_layers
            || self.decoder.future_receptive.len() != self.decoder.num_layers
        {
            return Err(crate::Error::Config(format!(
                "past/future receptive fields must have one entry per layer ({} layers, got P={}, F={})",
                self.decoder.num_layers,
                self.decoder.past_receptive.len(),
                self.decoder.future_receptive.len(),
            )));
        }
        if self.decoder.hidden_dim % self.decoder.num_heads != 0 {
            return Err(crate::Error::Config(
                "decoder hidden_dim must be divisible by num_heads".into(),
            ));
        }
        if self.utte.hidden_dim % self.utte.num_heads != 0 {
            return Err(crate::Error::Config(
                "UTTE hidden_dim must be divisible by num_heads".into(),
            ));
        }
        if self.decoder.n_mels != self.mel.n_mels {
            return Err(crate::Error::Config(
                "decoder.n_mels must match mel.n_mels".into(),
            ));
        }
        if self.decoder.bnf_dim != self.utte.hidden_dim {
            return Err(crate::Error::Config(
                "decoder.bnf_dim must match utte.hidden_dim (the decoder is \
                 conditioned on UTTE outputs)"
                    .into(),
            ));
        }
        if self.decoder.speaker_dim != self.utte.speaker_dim {
            return Err(crate::Error::Config(
                "decoder.speaker_dim must match utte.speaker_dim".into(),
            ));
        }
        Ok(())
    }
}
