//! Golden tests against PyTorch references (issues #8 and #14).
//!
//! Two fixture tiers:
//!
//! * **Committed** fixtures under `tools/fixtures/` (small, generated by
//!   `tools/gen_*_fixture.py`) — always exercised by `cargo test`.
//! * **Checkpoint-dependent** fixtures under `ckpt/` (generated by
//!   `tools/gen_v1_fixtures.py` from the official ASLP-lab/MeanVC release)
//!   — the v1 parity suite. These need the official checkpoints, so the
//!   tests skip with a message when a file is absent and the default
//!   suite stays green without them.

use std::collections::HashMap;
use std::path::PathBuf;

use candle_core::{forward_ad::jvp, Device, Tensor, Var, D};

fn fixture(name: &str) -> Option<HashMap<String, Tensor>> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tools/fixtures")
        .join(name);
    if !path.exists() {
        eprintln!("skipping: fixture {name} not found — generate it with tools/gen_*_fixture.py");
        return None;
    }
    Some(candle_core::safetensors::load(&path, &Device::Cpu).unwrap())
}

/// Path to a file under `ckpt/` (official checkpoints + v1 parity
/// fixtures); `None` (skip) when it has not been downloaded/generated.
fn ckpt_path(name: &str) -> Option<PathBuf> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("ckpt")
        .join(name);
    if !path.exists() {
        eprintln!(
            "skipping: ckpt/{name} not found — download the official checkpoints and run \
             tools/gen_v1_fixtures.py (see tools/README.md)"
        );
        return None;
    }
    Some(path)
}

fn ckpt_fixture(name: &str) -> Option<HashMap<String, Tensor>> {
    ckpt_path(name).map(|p| candle_core::safetensors::load(&p, &Device::Cpu).unwrap())
}

/// `ckpt/test.wav` as mono f32 samples in `[-1, 1]`.
fn test_wav() -> Option<Vec<f32>> {
    let path = ckpt_path("test.wav")?;
    let mut reader = hound::WavReader::open(path).unwrap();
    Some(
        reader
            .samples::<i16>()
            .map(|s| s.unwrap() as f32 / 32768.0)
            .collect(),
    )
}

fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
    (a - b)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar()
        .unwrap()
}

/// Mirrors `f` in `tools/gen_jvp_fixture.py`: linear → silu → layernorm →
/// self-attention → residual → timestep modulation → tanh → linear.
fn mini_dit(w: &HashMap<String, Tensor>, x: &Tensor, t: &Tensor) -> candle_core::Result<Tensor> {
    let lin = |h: &Tensor, wname: &str, bname: &str| -> candle_core::Result<Tensor> {
        h.broadcast_matmul(&w[wname].t()?)?.broadcast_add(&w[bname])
    };
    let h = lin(x, "w1", "b1")?.silu()?;
    // Layer norm without affine, eps 1e-5.
    let mean = h.mean_keepdim(D::Minus1)?;
    let h = h.broadcast_sub(&mean)?;
    let var = h.sqr()?.mean_keepdim(D::Minus1)?;
    let h = h.broadcast_div(&(var + 1e-5)?.sqrt()?)?;

    let d_h = h.dim(D::Minus1)?;
    let q = lin(&h, "wq", "bq")?;
    let k = lin(&h, "wk", "bk")?;
    let v = lin(&h, "wv", "bv")?;
    let scores = (q.matmul(&k.transpose(1, 2)?.contiguous()?)? / (d_h as f64).sqrt())?;
    let a = candle_nn::ops::softmax(&scores, D::Minus1)?;
    let h = (h + a.matmul(&v)?)?;

    let (b, _, _) = h.dims3()?;
    let h = h.broadcast_mul(&(t + 1.0)?.reshape((b, 1, 1))?)?;
    lin(&h.tanh()?, "w2", "b2")
}

#[test]
fn jvp_matches_torch_func_jvp() {
    let Some(fx) = fixture("jvp.safetensors") else {
        return;
    };
    let x = Var::from_tensor(&fx["x"]).unwrap();
    let t = Var::from_tensor(&fx["t"]).unwrap();

    let y = mini_dit(&fx, x.as_tensor(), t.as_tensor()).unwrap();
    let forward_diff = max_abs_diff(&y, &fx["y_ref"]);
    assert!(
        forward_diff < 1e-5,
        "forward pass diverges from PyTorch: {forward_diff}"
    );

    let dy = jvp(
        &y,
        &[(x.as_tensor(), &fx["vx"]), (t.as_tensor(), &fx["vt"])],
    )
    .unwrap();
    let jvp_diff = max_abs_diff(&dy, &fx["jvp_ref"]);
    assert!(
        jvp_diff < 1e-4,
        "candle forward-AD JVP diverges from torch.func.jvp: {jvp_diff}"
    );
}

// ---------------------------------------------------------------------------
// MeanVC v1 parity suite (issue #14): Rust ports vs the official
// ASLP-lab/MeanVC release. Fixtures are generated by
// `tools/gen_v1_fixtures.py` into `ckpt/`; every test skips when its
// checkpoint/fixture is missing.
// ---------------------------------------------------------------------------

fn load_v1_dit() -> Option<meanvc2::v1::MeanVc1> {
    let path = ckpt_path("model_200ms.safetensors")?;
    Some(
        meanvc2::v1::MeanVc1::load(meanvc2::v1::MeanVc1Config::default(), path, &Device::Cpu)
            .unwrap(),
    )
}

/// Single non-streaming DiT forward (`u(x, r=0, t=1)`, no cache) against
/// the official `dit_kvcache.py` DiT.
#[test]
fn v1_dit_forward_matches_official() {
    let Some(fx) = ckpt_fixture("dit_fixture.safetensors") else {
        return;
    };
    let Some(model) = load_v1_dit() else { return };
    let timbre = model
        .timbre_cond(&fx["bn"], &fx["prompts"], &fx["spks"])
        .unwrap();
    let r = Tensor::zeros((1,), candle_core::DType::F32, &Device::Cpu).unwrap();
    let t = Tensor::ones((1,), candle_core::DType::F32, &Device::Cpu).unwrap();
    let u = model
        .forward(
            &fx["x"],
            &timbre,
            &fx["spks"],
            meanvc2::v1::CacheLayout::None,
            &r,
            &t,
        )
        .unwrap();
    let diff = max_abs_diff(&u, &fx["u_ref"]);
    assert!(diff < 1e-4, "v1 DiT forward diverges from official: {diff}");
}

/// 8-chunk CARD streaming with the official KV-cache semantics
/// (per-block cache capped at `max_lookback * chunk_size = 100`).
#[test]
fn v1_dit_streaming_kv_cache_matches_official() {
    let Some(fx) = ckpt_fixture("dit_stream_fixture.safetensors") else {
        return;
    };
    let Some(model) = load_v1_dit() else { return };
    let timbre = model
        .timbre_cond(&fx["bn"], &fx["prompts"], &fx["spks"])
        .unwrap();
    let cs = model.config().chunk_size;
    let mut kv = meanvc2::v1::KvCache::default();
    let mut prev: Option<Tensor> = None;
    for q in 0..8 {
        let noise = &fx[&format!("n{q}")];
        let u = model
            .forward_stream(
                noise,
                &timbre.narrow(1, q * cs, cs).unwrap(),
                &fx["spks"],
                prev.as_ref(),
                q * cs,
                &mut kv,
            )
            .unwrap();
        let diff = max_abs_diff(&u, &fx[&format!("u{q}")]);
        assert!(
            diff < 1e-4,
            "v1 streaming chunk {q} diverges from official: {diff}"
        );
        prev = Some((noise - u).unwrap());
    }
}

/// Official v1 mel front-end (`MelSpectrogramFeatures`: magnitude STFT →
/// slaney filterbank → dB → `[-1, 1]` normalization).
#[test]
fn v1_mel_matches_official() {
    let Some(fx) = ckpt_fixture("copysyn_fixture.safetensors") else {
        return;
    };
    let Some(wav) = test_wav() else { return };
    let ours = meanvc2::v1::MelV1::new()
        .compute(&wav, &Device::Cpu)
        .unwrap();
    let theirs = &fx["mel_raw"];
    let n = ours.dim(0).unwrap().min(theirs.dim(0).unwrap());
    let diff = max_abs_diff(
        &ours.narrow(0, 0, n).unwrap(),
        &theirs.narrow(0, 0, n).unwrap(),
    );
    assert!(diff < 1e-4, "v1 mel diverges from official: {diff}");
}

/// Vocos copy-synthesis: the official mel through our `backends::Vocos`
/// vs the official TorchScript vocoder's waveform.
#[test]
fn v1_vocos_copy_synthesis_matches_official() {
    use meanvc2::encoders::Vocoder;
    let Some(fx) = ckpt_fixture("copysyn_fixture.safetensors") else {
        return;
    };
    let Some(weights) = ckpt_path("vocos.safetensors") else {
        return;
    };
    let vocos = meanvc2::backends::Vocos::load(
        meanvc2::backends::VocosConfig::official_meanvc1(),
        weights,
        &Device::Cpu,
    )
    .unwrap();
    let wav = vocos.synthesize(&fx["mel01"]).unwrap();
    let wav_ref: Vec<f32> = fx["wav_ref"].to_vec1().unwrap();
    let n = wav.len().min(wav_ref.len());
    assert!(n > 0, "empty synthesis output");
    let diff = wav[..n]
        .iter()
        .zip(&wav_ref[..n])
        .map(|(a, b)| (a - b).abs())
        .fold(0f32, f32::max);
    assert!(diff < 5e-3, "Vocos waveform diverges from official: {diff}");
}

/// Kaldi log-mel filterbank front-end vs `torchaudio.compliance.kaldi.fbank`
/// (25 ms / 10 ms, dither 0, snip_edges, int16-scaled input).
#[test]
fn v1_kaldi_fbank_matches_torchaudio() {
    let Some(fx) = ckpt_fixture("pipeline_ref.safetensors") else {
        return;
    };
    let Some(fbank_ref) = fx.get("fbank_ref") else {
        eprintln!(
            "skipping: pipeline_ref.safetensors has no fbank_ref — regenerate with tools/gen_v1_fixtures.py"
        );
        return;
    };
    let Some(wav) = test_wav() else { return };
    let ours = meanvc2::v1::KaldiFbank::new()
        .compute(&wav, &Device::Cpu)
        .unwrap()
        .unsqueeze(0)
        .unwrap();
    assert_eq!(ours.dims(), fbank_ref.dims(), "fbank frame count mismatch");
    let diff = max_abs_diff(&ours, fbank_ref);
    assert!(diff < 1e-3, "kaldi fbank diverges from torchaudio: {diff}");
}

/// Full BNF path (kaldi fbank → Fast-U2++ → ×4 linear upsampling) vs the
/// official chunked decode loop (`infer_ref.py`: 5-frame chunks, 2 left
/// chunks, ×4 subsampling). Our full-utterance forward recomputes each
/// chunk in its bounded window instead of caching, so the tolerance is
/// looser than the per-chunk checks.
#[test]
fn v1_bnf_pipeline_matches_official() {
    use meanvc2::v1::{interpolate_linear, KaldiFbank};
    let Some(fx) = ckpt_fixture("pipeline_ref.safetensors") else {
        return;
    };
    let Some(weights) = ckpt_path("fastu2pp.safetensors") else {
        return;
    };
    let Some(wav) = test_wav() else { return };
    let fbank = KaldiFbank::new()
        .compute(&wav, &Device::Cpu)
        .unwrap()
        .unsqueeze(0)
        .unwrap();
    let asr = meanvc2::backends::FastU2pp::load(
        meanvc2::backends::FastU2ppConfig::official_meanvc1(),
        weights,
        &Device::Cpu,
    )
    .unwrap();
    let bn = interpolate_linear(&asr.forward(&fbank).unwrap(), 4).unwrap();
    let bn_ref = &fx["bn_ref"];
    let n = bn.dim(1).unwrap().min(bn_ref.dim(1).unwrap());
    let diff = max_abs_diff(
        &bn.narrow(1, 0, n).unwrap(),
        &bn_ref.narrow(1, 0, n).unwrap(),
    );
    assert!(diff < 0.05, "end-to-end BNF diverges from official: {diff}");
}

/// Fast-U2++ stage-by-stage parity on the first decode chunk: subsampled
/// embedding, sinusoidal positional encoding, first conformer block, and
/// the full 7-layer chunk-0 output vs the official `forward_encoder_chunk`.
#[test]
fn v1_fast_u2pp_chunk0_stages_match_official() {
    let Some(fx) = ckpt_fixture("asr_chunk0_fixture.safetensors") else {
        return;
    };
    let Some(weights) = ckpt_path("fastu2pp.safetensors") else {
        return;
    };
    let asr = meanvc2::backends::FastU2pp::load(
        meanvc2::backends::FastU2ppConfig::official_meanvc1(),
        weights,
        &Device::Cpu,
    )
    .unwrap();

    // Conv2d subsampling ×4 (the official embed values are large, ~1e4,
    // so the absolute tolerance is scaled accordingly).
    let embed = asr.subsample(&fx["fb23"]).unwrap();
    let embed_diff = max_abs_diff(&embed, &fx["embed_ref"]);
    assert!(
        embed_diff < 1e-2,
        "subsampled embedding diverges from official: {embed_diff}"
    );

    let pe = meanvc2::backends::debug_sinusoidal_pe(5, 256, &Device::Cpu).unwrap();
    let pe_diff = max_abs_diff(&pe, &fx["pos"]);
    assert!(
        pe_diff < 1e-4,
        "sinusoidal positional encoding diverges from official: {pe_diff}"
    );

    let layer0 = asr.debug_layer0(&fx["x_embed"], &fx["pos"]).unwrap();
    let layer0_diff = max_abs_diff(&layer0, &fx["layer0_ref"]);
    assert!(
        layer0_diff < 1e-3,
        "conformer layer 0 diverges from official: {layer0_diff}"
    );

    let bn0 = asr.forward(&fx["fb23"]).unwrap();
    let bn0_diff = max_abs_diff(&bn0, &fx["bn0_ref"]);
    assert!(
        bn0_diff < 1e-3,
        "chunk-0 BNF diverges from official: {bn0_diff}"
    );
}
