//! Golden tests for the X-VC speaker encoder (issue #30) against the
//! official Jerrister/X-VC implementation.
//!
//! References live under `ckpt/` (gitignored):
//!
//! * `ckpt/xvc_speaker.safetensors` — the ERes2Net weights, converted with
//!   `tools/convert_xvc_speaker.py`;
//! * `ckpt/xvc_speaker_fixture.safetensors` — reference wav → Kaldi
//!   fbank-80 → 192-d embedding, generated by `tools/gen_xvc_fixtures.py`.
//!
//! Tests skip with a message when a file is absent so the default suite
//! stays green without checkpoints (same tiering as `meanvc`'s golden
//! suite). Tolerances per #30: fbank < 1e-3 abs, embedding cosine
//! similarity > 0.9999.

use std::collections::HashMap;
use std::path::PathBuf;

use candle_core::{Device, Tensor};
use xvc::speaker::{ERes2Net, KaldiFbank, SpeakerEncoder};

/// Path of `rel` at the workspace root (this crate lives two levels below
/// it, in `crates/xvc`); `ckpt/` is kept at the root.
fn ckpt_path(name: &str) -> Option<PathBuf> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("ckpt")
        .join(name);
    if !path.exists() {
        eprintln!(
            "skipping: ckpt/{name} not found — download the official checkpoints and run \
             tools/convert_xvc_speaker.py + tools/gen_xvc_fixtures.py (see tools/README.md)"
        );
        return None;
    }
    Some(path)
}

fn ckpt_fixture(name: &str) -> Option<HashMap<String, Tensor>> {
    ckpt_path(name).map(|p| candle_core::safetensors::load(&p, &Device::Cpu).unwrap())
}

fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
    (a - b)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar()
        .unwrap()
}

fn cosine(a: &Tensor, b: &Tensor) -> f32 {
    let a: Vec<f32> = a.flatten_all().unwrap().to_vec1().unwrap();
    let b: Vec<f32> = b.flatten_all().unwrap().to_vec1().unwrap();
    let dot: f32 = a.iter().zip(&b).map(|(x, y)| x * y).sum();
    let na: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
    let nb: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
    dot / (na * nb)
}

/// `ref_wav` from the fixture as a flat sample vector.
fn ref_samples(fx: &HashMap<String, Tensor>) -> Vec<f32> {
    fx["ref_wav"].flatten_all().unwrap().to_vec1().unwrap()
}

/// Kaldi fbank-80 (dither 0, utterance mean-norm) vs
/// `torchaudio.compliance.kaldi.fbank` on the reference wav.
#[test]
fn xvc_speaker_fbank_matches_official() {
    let Some(fx) = ckpt_fixture("xvc_speaker_fixture.safetensors") else {
        return;
    };
    let fbank = KaldiFbank::new()
        .compute(&ref_samples(&fx), &Device::Cpu)
        .unwrap();
    let reference = fx["fbank"].squeeze(0).unwrap(); // (382, 80)
    assert_eq!(fbank.dims(), reference.dims());
    let diff = max_abs_diff(&fbank, &reference);
    println!("fbank max abs diff: {diff:.3e}");
    assert!(diff < 1e-3, "fbank max abs diff {diff} >= 1e-3");
}

/// ERes2Net alone on the *fixture* fbank (front end bypassed) — isolates
/// the network from the DSP.
#[test]
fn xvc_speaker_eres2net_matches_official() {
    let Some(fx) = ckpt_fixture("xvc_speaker_fixture.safetensors") else {
        return;
    };
    let Some(weights) = ckpt_path("xvc_speaker.safetensors") else {
        return;
    };
    let model = ERes2Net::load(weights, &Device::Cpu).unwrap();
    let emb = model.forward(&fx["fbank"]).unwrap(); // (1, 192)
    let reference = &fx["embedding"];
    assert_eq!(emb.dims(), reference.dims());
    let diff = max_abs_diff(&emb, reference);
    let cos = cosine(&emb, reference);
    println!("eres2net embedding max abs diff: {diff:.3e}, cosine: {cos:.7}");
    assert!(cos > 0.9999, "embedding cosine {cos} <= 0.9999");
    assert!(diff < 1e-3, "embedding max abs diff {diff} >= 1e-3");
}

/// Full pipeline: reference wav → fbank → ERes2Net → 192-d embedding.
#[test]
fn xvc_speaker_embedding_matches_official() {
    let Some(fx) = ckpt_fixture("xvc_speaker_fixture.safetensors") else {
        return;
    };
    let Some(weights) = ckpt_path("xvc_speaker.safetensors") else {
        return;
    };
    let encoder = SpeakerEncoder::load(weights, &Device::Cpu).unwrap();
    let emb = encoder.embed(&ref_samples(&fx)).unwrap(); // (1, 192)
    let reference = &fx["embedding"];
    assert_eq!(emb.dims(), reference.dims());
    let diff = max_abs_diff(&emb, reference);
    let cos = cosine(&emb, reference);
    println!("embedding max abs diff: {diff:.3e}, cosine: {cos:.7}");
    assert!(cos > 0.9999, "embedding cosine {cos} <= 0.9999");
    assert!(diff < 1e-3, "embedding max abs diff {diff} >= 1e-3");
}
