//! Golden tests for the X-VC preprocessing + GLM-4-Voice tokenizer port
//! (issue #30 Phase 1) against the PyTorch references generated by
//! `tools/gen_xvc_fixtures.py`.
//!
//! Checkpoint-dependent (skip-if-absent, like `crates/meanvc/tests/golden.rs`):
//! the fixtures live under `ckpt/` at the workspace root and the model
//! weights in `ckpt/xvc_tokenizer.safetensors` (generated by
//! `tools/convert_xvc_tokenizer.py`).
//!
//! Tolerances per the issue #30 fixture inventory: processed wav < 1e-5,
//! mel < 1e-4, tokenizer hidden states < 1e-3 (16-layer Whisper-large
//! stack), `token_ids` exact, `sem_emb` / `adapter_out` < 1e-4.

use std::collections::HashMap;
use std::path::PathBuf;

use candle_core::{DType, Device, Tensor};
use xvc::preprocess::{preprocess, PreprocessConfig, WhisperFeatureExtractor};
use xvc::tokenizer::{SemanticAdapter, WhisperVqEncoder};

/// Path of `rel` at the workspace root (this crate lives two levels below
/// it, in `crates/xvc`); `ckpt/` is kept at the root.
fn workspace_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(rel)
}

/// Path to a file under `ckpt/`; `None` (skip) when it is absent.
fn ckpt_path(name: &str) -> Option<PathBuf> {
    let path = workspace_path("ckpt").join(name);
    if !path.exists() {
        eprintln!(
            "skipping: ckpt/{name} not found — run tools/gen_xvc_fixtures.py / \
             tools/convert_xvc_tokenizer.py (see tools/README.md)"
        );
        return None;
    }
    Some(path)
}

fn ckpt_fixture(name: &str) -> Option<HashMap<String, Tensor>> {
    ckpt_path(name).map(|p| candle_core::safetensors::load(&p, &Device::Cpu).unwrap())
}

fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
    (a - b)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar()
        .unwrap()
}

/// Raw i16 fixture tensor -> the float64 samples `soundfile.read` yields.
fn raw_to_f64(raw: &Tensor) -> Vec<f64> {
    raw.to_dtype(DType::F64)
        .unwrap()
        .to_vec1::<f64>()
        .unwrap()
        .into_iter()
        .map(|s| s / 32768.0)
        .collect()
}

fn load_models() -> Option<(WhisperVqEncoder, SemanticAdapter)> {
    let path = ckpt_path("xvc_tokenizer.safetensors")?;
    let (enc, ada) = xvc::tokenizer::load(&path, &Device::Cpu).unwrap();
    Some((enc, ada))
}

/// Volume-norm + 40 Hz highpass + pad-to-1280, vs `processed_source` /
/// `processed_target` (< 1e-5 abs).
#[test]
fn preprocess_wav_golden() {
    let Some(fx) = ckpt_fixture("xvc_preprocess_fixture.safetensors") else {
        return;
    };
    let cfg = PreprocessConfig::default();
    for (raw, refname) in [
        ("raw_source_i16", "processed_source"),
        ("raw_target_i16", "processed_target"),
    ] {
        let samples = raw_to_f64(&fx[raw]);
        let processed = preprocess(&samples, &cfg);
        let want = fx[refname].flatten_all().unwrap();
        assert_eq!(processed.len(), want.dims1().unwrap(), "{refname} length");
        let got = Tensor::from_vec(processed, want.shape(), &Device::Cpu).unwrap();
        let diff = max_abs_diff(&got, &want);
        eprintln!("{refname}: max abs diff {diff:.3e}");
        assert!(diff < 1e-5, "{refname}: {diff}");
    }
}

/// Whisper 128-mel log spectrogram vs `mel_source` / `mel_chunk`
/// (< 1e-4 abs) and the frame attention masks (exact).
#[test]
fn whisper_mel_golden() {
    let Some(fx) = ckpt_fixture("xvc_preprocess_fixture.safetensors") else {
        return;
    };
    let extractor = WhisperFeatureExtractor::default();
    for (wav, mel_name, mask_name) in [
        ("processed_source", "mel_source", "mel_source_mask"),
        ("chunk_wav", "mel_chunk", "mel_chunk_mask"),
    ] {
        let samples = fx[wav].flatten_all().unwrap().to_vec1::<f32>().unwrap();
        let feats = extractor.extract(&samples, &Device::Cpu).unwrap();
        let want = &fx[mel_name];
        assert_eq!(feats.input_features.dims(), want.dims(), "{mel_name} shape");
        let diff = max_abs_diff(&feats.input_features, want);
        eprintln!("{mel_name}: max abs diff {diff:.3e}");
        assert!(diff < 1e-4, "{mel_name}: {diff}");

        let want_mask = fx[mask_name]
            .flatten_all()
            .unwrap()
            .to_vec1::<i32>()
            .unwrap();
        let got_mask: Vec<i32> = feats.attention_mask.iter().map(|&m| m as i32).collect();
        assert_eq!(got_mask, want_mask, "{mask_name}");
    }
}

/// Tokenizer forward on the 640 ms chunk mel: 50 Hz hidden, pre-VQ hidden
/// (< 1e-3), token ids (exact), post-VQ hidden (< 1e-3). Also reports the
/// per-chunk wall time (the 640 ms CPU streaming preset unit of work).
#[test]
fn tokenizer_chunk_golden() {
    let Some(fx) = ckpt_fixture("xvc_tokenizer_fixture.safetensors") else {
        return;
    };
    let Some((encoder, _)) = load_models() else {
        return;
    };
    let mask: Vec<u32> = fx["mel_mask"]
        .flatten_all()
        .unwrap()
        .to_vec1::<i32>()
        .unwrap()
        .into_iter()
        .map(|m| m as u32)
        .collect();
    let out = encoder.forward(&fx["mel"], &mask).unwrap(); // warm-up
    let start = std::time::Instant::now();
    const REPS: usize = 5;
    for _ in 0..REPS {
        encoder.forward(&fx["mel"], &mask).unwrap();
    }
    eprintln!(
        "tokenizer forward (640 ms chunk): {:.1} ms/chunk (mean of {REPS})",
        start.elapsed().as_secs_f64() * 1e3 / REPS as f64
    );
    for (got, name, tol) in [
        (&out.hidden_50hz, "hidden_50hz", 1e-3),
        (&out.hidden_prevq, "hidden_prevq", 1e-3),
        (&out.hidden_postvq, "hidden_postvq", 1e-3),
    ] {
        assert_eq!(got.dims(), fx[name].dims(), "{name} shape");
        let diff = max_abs_diff(got, &fx[name]);
        eprintln!("{name}: max abs diff {diff:.3e}");
        assert!(diff < tol, "{name}: {diff}");
    }
    let got_ids = out.token_ids.to_vec2::<i64>().unwrap();
    let want_ids = fx["token_ids"].to_vec2::<i64>().unwrap();
    assert_eq!(got_ids, want_ids, "token_ids");
}

/// Tokenizer forward on the full 4.08 s utterance — 204 pre-pool frames
/// span two block-causal blocks (block = 200), exercising the mask across
/// a block boundary.
#[test]
fn tokenizer_full_utterance_golden() {
    let Some(fx) = ckpt_fixture("xvc_tokenizer_fixture.safetensors") else {
        return;
    };
    let Some((encoder, _)) = load_models() else {
        return;
    };
    let mask: Vec<u32> = fx["full_mel_mask"]
        .flatten_all()
        .unwrap()
        .to_vec1::<i32>()
        .unwrap()
        .into_iter()
        .map(|m| m as u32)
        .collect();
    let out = encoder.forward(&fx["full_mel"], &mask).unwrap();
    for (got, name, tol) in [
        (&out.hidden_50hz, "full_hidden_50hz", 1e-3),
        (&out.hidden_prevq, "full_hidden_prevq", 1e-3),
        (&out.hidden_postvq, "full_hidden_postvq", 1e-3),
    ] {
        assert_eq!(got.dims(), fx[name].dims(), "{name} shape");
        let diff = max_abs_diff(got, &fx[name]);
        eprintln!("{name}: max abs diff {diff:.3e}");
        assert!(diff < tol, "{name}: {diff}");
    }
    let got_ids = out.token_ids.to_vec2::<i64>().unwrap();
    let want_ids = fx["full_token_ids"].to_vec2::<i64>().unwrap();
    assert_eq!(got_ids, want_ids, "full_token_ids");
}

/// `embed_ids` (codebook lookup) vs `sem_emb` and the semantic adapter
/// (12.5 -> 50 Hz) vs `adapter_out`, both < 1e-4 abs.
#[test]
fn semantic_adapter_golden() {
    let Some(fx) = ckpt_fixture("xvc_tokenizer_fixture.safetensors") else {
        return;
    };
    let Some((encoder, adapter)) = load_models() else {
        return;
    };
    let sem_emb = encoder.embed_ids(&fx["token_ids"]).unwrap();
    assert_eq!(sem_emb.dims(), fx["sem_emb"].dims(), "sem_emb shape");
    let diff = max_abs_diff(&sem_emb, &fx["sem_emb"]);
    eprintln!("sem_emb: max abs diff {diff:.3e}");
    assert!(diff < 1e-4, "sem_emb: {diff}");

    let sem_emb_t = sem_emb.transpose(1, 2).unwrap();
    let adapter_out = adapter.forward(&sem_emb_t).unwrap(); // warm-up
    let start = std::time::Instant::now();
    const REPS: usize = 5;
    for _ in 0..REPS {
        adapter.forward(&sem_emb_t).unwrap();
    }
    eprintln!(
        "semantic adapter forward (640 ms chunk): {:.1} ms/chunk (mean of {REPS})",
        start.elapsed().as_secs_f64() * 1e3 / REPS as f64
    );
    assert_eq!(
        adapter_out.dims(),
        fx["adapter_out"].dims(),
        "adapter_out shape"
    );
    let diff = max_abs_diff(&adapter_out, &fx["adapter_out"]);
    eprintln!("adapter_out: max abs diff {diff:.3e}");
    assert!(diff < 1e-4, "adapter_out: {diff}");
}

/// End to end across the two fixtures: preprocessed chunk wav -> Rust mel
/// -> tokenizer -> token ids, exact vs the reference ids.
#[test]
fn chunk_wav_to_token_ids_golden() {
    let Some(pre) = ckpt_fixture("xvc_preprocess_fixture.safetensors") else {
        return;
    };
    let Some(tok) = ckpt_fixture("xvc_tokenizer_fixture.safetensors") else {
        return;
    };
    let Some((encoder, _)) = load_models() else {
        return;
    };
    let samples = pre["chunk_wav"]
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .unwrap();
    let extractor = WhisperFeatureExtractor::default();
    let feats = extractor.extract(&samples, &Device::Cpu).unwrap();
    let out = encoder
        .forward(&feats.input_features, &feats.attention_mask)
        .unwrap();
    let got_ids = out.token_ids.to_vec2::<i64>().unwrap();
    let want_ids = tok["token_ids"].to_vec2::<i64>().unwrap();
    assert_eq!(got_ids, want_ids, "wav -> mel -> token_ids");
}
