//! Golden tests for the SAC acoustic codec (`xvc::codec`) against the
//! official X-VC PyTorch implementation (issue #30, Phase 1).
//!
//! References are generated by `tools/gen_xvc_fixtures.py` into `ckpt/`
//! (gitignored) and the weights by `tools/convert_xvc_generator.py`; every
//! test skips with a message when a file is absent so the default suite
//! stays green without the official checkpoints.

mod util;

use candle_core::{DType, D};
use util::{ckpt_fixture, ckpt_path, max_abs_diff};
use xvc::SacCodec;

fn codec() -> Option<SacCodec> {
    let path = ckpt_path("xvc_codec.safetensors")?;
    Some(SacCodec::load(path, &candle_core::Device::Cpu).unwrap())
}

/// Encode: chunk wav `[1, 1, 10240]` -> DAC encoder latent `z`
/// `[1, 1024, 32]` -> FVQ (`z_e` projected latents, `codes` ids, `zq`
/// out-projected quantized latents). Tolerances per #30: continuous
/// tensors < 1e-4 abs, codes exact.
#[test]
fn codec_encode_matches_official() {
    let (Some(codec), Some(fx)) = (codec(), ckpt_fixture("xvc_codec_fixture.safetensors")) else {
        return;
    };
    // Warm-up, then a timed run (one 640 ms chunk).
    let enc = codec.encode(&fx["chunk_wav"]).unwrap();
    let start = std::time::Instant::now();
    let _ = codec.encode(&fx["chunk_wav"]).unwrap();
    eprintln!(
        "encode 640 ms chunk: {:.1} ms",
        start.elapsed().as_secs_f64() * 1e3
    );

    let (dz, dze, dzq) = (
        max_abs_diff(&enc.z, &fx["z"]),
        max_abs_diff(&enc.z_e, &fx["z_e"]),
        max_abs_diff(&enc.zq, &fx["zq"]),
    );
    eprintln!("encode max abs diff: z {dz:.2e}, z_e {dze:.2e}, zq {dzq:.2e}");
    assert!(dz < 1e-4, "z max abs diff {dz}");
    assert!(dze < 1e-4, "z_e max abs diff {dze}");
    assert!(dzq < 1e-4, "zq max abs diff {dzq}");

    let codes = enc.codes.to_dtype(DType::I64).unwrap();
    let diff = codes
        .ne(&fx["codes"])
        .unwrap()
        .to_dtype(DType::F32)
        .unwrap()
        .sum_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    assert_eq!(diff, 0.0, "codes must match exactly");
}

/// Decode: converter-output latent `[1, 1024, 32]` -> 16 kHz waveform
/// `[1, 1, 10240]` (tolerance < 5e-3 abs, the Vocos wav precedent).
/// Also reports the wall time of one 640 ms chunk decode.
#[test]
fn codec_decode_matches_official() {
    let (Some(codec), Some(fx)) = (codec(), ckpt_fixture("xvc_codec_fixture.safetensors")) else {
        return;
    };
    // Warm-up, then a timed run (one 640 ms chunk).
    let wav = codec.decode(&fx["dec_in"]).unwrap();
    let start = std::time::Instant::now();
    let _ = codec.decode(&fx["dec_in"]).unwrap();
    eprintln!(
        "decode 640 ms chunk: {:.1} ms",
        start.elapsed().as_secs_f64() * 1e3
    );

    assert_eq!(wav.dims(), fx["dec_out"].dims());
    let diff = max_abs_diff(&wav, &fx["dec_out"]);
    eprintln!("decode max abs diff: dec_out {diff:.2e}");
    assert!(diff < 5e-3, "dec_out max abs diff {diff}");
}

/// The encoder output frame rate is 50 Hz (320x downsampling): 10240
/// samples -> 32 latent frames, and z has 1024 channels.
#[test]
fn codec_encode_shapes() {
    let (Some(codec), Some(fx)) = (codec(), ckpt_fixture("xvc_codec_fixture.safetensors")) else {
        return;
    };
    let enc = codec.encode(&fx["chunk_wav"]).unwrap();
    assert_eq!(enc.z.dims(), &[1, 1024, 32]);
    assert_eq!(enc.z_e.dims(), &[1, 8, 32]);
    assert_eq!(enc.codes.dims(), &[1, 32]);
    assert_eq!(enc.zq.dims(), &[1, 1024, 32]);
    // decode inverts the rate: 32 frames -> 10240 samples in [-1, 1].
    let wav = codec.decode(&enc.zq).unwrap();
    assert_eq!(wav.dims(), &[1, 1, 10240]);
    let peak = wav
        .abs()
        .unwrap()
        .max(D::Minus1)
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    assert!(peak <= 1.0, "tanh output must stay in [-1, 1]");
}
